/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as IndexRouteImport } from './routes/index'

const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/insights': typeof InsightsRoute
  '/payments': typeof PaymentsRoute
  '/savings': typeof SavingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/insights': typeof InsightsRoute
  '/payments': typeof PaymentsRoute
  '/savings': typeof SavingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/insights': typeof InsightsRoute
  '/payments': typeof PaymentsRoute
  '/savings': typeof SavingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cards' | '/insights' | '/payments' | '/savings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cards' | '/insights' | '/payments' | '/savings'
  id: '__root__' | '/' | '/cards' | '/insights' | '/payments' | '/savings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsRoute: typeof CardsRoute
  InsightsRoute: typeof InsightsRoute
  PaymentsRoute: typeof PaymentsRoute
  SavingsRoute: typeof SavingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsRoute: CardsRoute,
  InsightsRoute: InsightsRoute,
  PaymentsRoute: PaymentsRoute,
  SavingsRoute: SavingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
